Dishes
CraftAcademy/feb17-slow-food-sinatra pull request #31
Opened 2017-02-22 16:54 UTC by fabianlundgren

Changes proposed in this pull request:

Added content to menu.erb to display Our Menu, dishes and price.
Cucumber and rspec tests are passing.

Ready for review!

@AmberWilkie

2017-02-22 20:01 UTC, tochman requested changes

2017-02-22 20:01 UTC, tochman commented on features/menu_on_menu_page.feature
> +  And I should see "Kebab" with "30"
Please format your code with correct indents. This in a no go on my part.

2017-02-22 20:01 UTC, tochman commented on features/step_definitions/test_steps.rb
> +end
Same here, please be mindful of code formatting.

2017-02-22 20:01 UTC, tochman commented on lib/controller.rb
> +
If you won't be using this method, please remove it. Not cool to keep comments around.

2017-02-22 20:01 UTC, tochman commented on lib/views/login.erb
> +</form> -->
Same thing here. If you don't use this view template, please delete it.

2017-02-22 20:01 UTC, tochman commented on lib/views/menu.erb
> +<% end %>
Please be mindful of empty spaces and code formatting.

2017-02-22 20:01 UTC, tochman commented on spec/spec_helper.rb
> +end
I know that this is auto generated code but I would encourage you to remove the comments.

2017-02-23 10:04 UTC, AmberWilkie commented on features/step_definitions/test_steps.rb
> +end
Formatting here is a problem - if you ever have two `end` statements stacked on each other like this, it means there is an indentation problem. This block should look like:
```
Given(/^the following dishes exist$/) do |table|
  table.hashes.each do | dish |
    Dish.create(dish)
  end
end
```
See how that demonstrates that the `Dish.create(dish)` is *inside* the `table.hashes` block? That's what we mean about "readability"

2017-02-23 10:05 UTC, AmberWilkie commented on lib/controller.rb
>    end
You should only have one `get '/auth/login' block.

2017-02-23 13:25 UTC, merged